[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/675666420",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4824#issuecomment-675666420",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4824",
        "id": 675666420,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY3NTY2NjQyMA==",
        "user": {
            "login": "YUNQIUGUO",
            "id": 35738743,
            "node_id": "MDQ6VXNlcjM1NzM4NzQz",
            "avatar_url": "https://avatars.githubusercontent.com/u/35738743?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/YUNQIUGUO",
            "html_url": "https://github.com/YUNQIUGUO",
            "followers_url": "https://api.github.com/users/YUNQIUGUO/followers",
            "following_url": "https://api.github.com/users/YUNQIUGUO/following{/other_user}",
            "gists_url": "https://api.github.com/users/YUNQIUGUO/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/YUNQIUGUO/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/YUNQIUGUO/subscriptions",
            "organizations_url": "https://api.github.com/users/YUNQIUGUO/orgs",
            "repos_url": "https://api.github.com/users/YUNQIUGUO/repos",
            "events_url": "https://api.github.com/users/YUNQIUGUO/events{/privacy}",
            "received_events_url": "https://api.github.com/users/YUNQIUGUO/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-08-18T19:21:13Z",
        "updated_at": "2020-08-18T19:21:13Z",
        "author_association": "MEMBER",
        "body": "@mikecaraman Hi, I tested the e2e example on my end using ResNet50_v1.onnx under ./E2E_example_model/resnet50_v1.onnx. I didn't find the KeyError issue. May I ask for further details?\r\n\r\nAlso, are you using the most up-to-date calibrate.py script?\r\n\r\nThanks!\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/675666420/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/675956922",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4824#issuecomment-675956922",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4824",
        "id": 675956922,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY3NTk1NjkyMg==",
        "user": {
            "login": "mikecaraman",
            "id": 56535429,
            "node_id": "MDQ6VXNlcjU2NTM1NDI5",
            "avatar_url": "https://avatars.githubusercontent.com/u/56535429?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mikecaraman",
            "html_url": "https://github.com/mikecaraman",
            "followers_url": "https://api.github.com/users/mikecaraman/followers",
            "following_url": "https://api.github.com/users/mikecaraman/following{/other_user}",
            "gists_url": "https://api.github.com/users/mikecaraman/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mikecaraman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mikecaraman/subscriptions",
            "organizations_url": "https://api.github.com/users/mikecaraman/orgs",
            "repos_url": "https://api.github.com/users/mikecaraman/repos",
            "events_url": "https://api.github.com/users/mikecaraman/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mikecaraman/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-08-19T08:41:07Z",
        "updated_at": "2020-08-19T08:41:07Z",
        "author_association": "CONTRIBUTOR",
        "body": "I am using master branch tip with the improvements from July. I am also able to reproduce the issue with calibrate.py script directly.\r\nThe input model is the one provided in the E2E_example_model. Can the issue be caused by the calibration data set?\r\nI am using python 3.5.2 on a x86_64 system with Ubuntu 16.04.\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/675956922/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/675973446",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4824#issuecomment-675973446",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4824",
        "id": 675973446,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY3NTk3MzQ0Ng==",
        "user": {
            "login": "YUNQIUGUO",
            "id": 35738743,
            "node_id": "MDQ6VXNlcjM1NzM4NzQz",
            "avatar_url": "https://avatars.githubusercontent.com/u/35738743?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/YUNQIUGUO",
            "html_url": "https://github.com/YUNQIUGUO",
            "followers_url": "https://api.github.com/users/YUNQIUGUO/followers",
            "following_url": "https://api.github.com/users/YUNQIUGUO/following{/other_user}",
            "gists_url": "https://api.github.com/users/YUNQIUGUO/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/YUNQIUGUO/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/YUNQIUGUO/subscriptions",
            "organizations_url": "https://api.github.com/users/YUNQIUGUO/orgs",
            "repos_url": "https://api.github.com/users/YUNQIUGUO/repos",
            "events_url": "https://api.github.com/users/YUNQIUGUO/events{/privacy}",
            "received_events_url": "https://api.github.com/users/YUNQIUGUO/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-08-19T08:52:30Z",
        "updated_at": "2020-08-19T08:52:30Z",
        "author_association": "MEMBER",
        "body": "> I am using master branch tip with the improvements from July. I am also able to reproduce the issue with calibrate.py script directly.\r\n> The input model is the one provided in the E2E_example_model. Can the issue be caused by the calibration data set?\r\n> I am using python 3.5.2 on a x86_64 system with Ubuntu 16.04.\r\n\r\nOkay, I see. Thanks for sharing. Btw, what calibration test data set are you using?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/675973446/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]