[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/902820258",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/8789#issuecomment-902820258",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/8789",
        "id": 902820258,
        "node_id": "IC_kwDOCVq1mM41z_Gi",
        "user": {
            "login": "chenfucn",
            "id": 1316708,
            "node_id": "MDQ6VXNlcjEzMTY3MDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1316708?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/chenfucn",
            "html_url": "https://github.com/chenfucn",
            "followers_url": "https://api.github.com/users/chenfucn/followers",
            "following_url": "https://api.github.com/users/chenfucn/following{/other_user}",
            "gists_url": "https://api.github.com/users/chenfucn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/chenfucn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/chenfucn/subscriptions",
            "organizations_url": "https://api.github.com/users/chenfucn/orgs",
            "repos_url": "https://api.github.com/users/chenfucn/repos",
            "events_url": "https://api.github.com/users/chenfucn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/chenfucn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-08-20T16:42:44Z",
        "updated_at": "2021-08-20T16:42:44Z",
        "author_association": "MEMBER",
        "body": "could you also share your python code snippets causing the error and the detailed error messages?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/902820258/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/903247840",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/8789#issuecomment-903247840",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/8789",
        "id": 903247840,
        "node_id": "IC_kwDOCVq1mM411nfg",
        "user": {
            "login": "nicholim",
            "id": 48317208,
            "node_id": "MDQ6VXNlcjQ4MzE3MjA4",
            "avatar_url": "https://avatars.githubusercontent.com/u/48317208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nicholim",
            "html_url": "https://github.com/nicholim",
            "followers_url": "https://api.github.com/users/nicholim/followers",
            "following_url": "https://api.github.com/users/nicholim/following{/other_user}",
            "gists_url": "https://api.github.com/users/nicholim/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nicholim/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nicholim/subscriptions",
            "organizations_url": "https://api.github.com/users/nicholim/orgs",
            "repos_url": "https://api.github.com/users/nicholim/repos",
            "events_url": "https://api.github.com/users/nicholim/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nicholim/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-08-22T10:37:37Z",
        "updated_at": "2021-08-22T10:37:37Z",
        "author_association": "NONE",
        "body": "Actually, I am trying to utilize the InsightFace library with the code as follows:\r\n```\r\nimport cv2\r\nimport numpy as np\r\nimport insightface\r\nfrom insightface.app import FaceAnalysis\r\nfrom insightface.data import get_image as ins_get_image\r\n\r\n# Method-1, use FaceAnalysis\r\napp = FaceAnalysis(allowed_modules=['detection']) # enable detection model only\r\napp.prepare(ctx_id=0, det_size=(640, 640))\r\n```\r\n\r\nThe error code is as follows:\r\n```\r\nTraceback (most recent call last):\r\n  File \"camtest.py\", line 243, in <module>\r\n    app = FaceAnalysis(allowed_modules=['detection']) # enable detection model only\r\n  File \"/usr/local/lib/python3.8/dist-packages/insightface/app/face_analysis.py\", line 26, in __init__\r\n    onnxruntime.set_default_logger_severity(3)\r\nAttributeError: module 'onnxruntime' has no attribute 'set_default_logger_severity'\r\n```\r\n\r\nHowever, as I mentioned earlier, `get_device` attribute also result in an error, for example when I call onnxruntime in this way:\r\n```\r\nimport onnxruntime as orts\r\nprint( ort.get_device())\r\n```\r\n\r\nThe error printed is as follows:\r\n```\r\nTraceback (most recent call last):\r\n  File \"testingonnx.py\", line 247, in <module>\r\n    print( ort.get_device())\r\nAttributeError: module 'onnxruntime' has no attribute 'get_device'\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/903247840/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]